name: Build and Test
on:
  push:
    branches:
      - develop
      - thachu
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint || echo "Linting completed with warnings"

    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production

    - name: Check build artifacts
      run: |
        if [ -d ".next" ]; then
          echo "Build successful - .next directory created"
          ls -la .next
        else
          echo "Build failed - .next directory not found"
          exit 1
        fi

    - name: Notify success
      if: success()
      run: echo "Build and test completed successfully"

    - name: Notify failure
      if: failure()
      run: echo "Build or test failed"

