name: Auto Pull Request Description

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-description:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit messages
        run: |
          commits=$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq -r '.commits[].messageHeadline' | sed 's/^/- /')
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$commits" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get suggested reviewers
        run: |
          reviewers=$(gh pr view ${{ github.event.pull_request.number }} --json reviewRequests --jq '.reviewRequests[].requestedReviewer.login' | tr '\n' ' ')
          if [ -z "$reviewers" ]; then
            reviewers="(none suggested)"
          fi
          echo "REVIEWERS<<EOF" >> $GITHUB_ENV
          echo "$reviewers" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR body
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --body "# 📌 Pull Request

            ## Description
            - ${{ github.event.pull_request.title }}

            ### Commits
            ${COMMITS}

            ### Reviewers
            - ${REVIEWERS}

            ## Checklist
            - [x] Code follows project style guidelines
            - [x] All pep8 standards have been followed
            - [x] Documentation updated
            - [x] Tests added/updated
            - [x] All existing tests pass

            ## Related Issue
            Fixes #"
